# https://docs.github.com/en/actions/using-workflows/about-workflows
name: Delivery

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+*'

jobs:
  # To share artifacts across jobs see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
  # Here I want to share artifacts across steps of a single job
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: package
        shell: bash
        run: |
          pwd && ls -la
          git clone --depth 1 --recursive --shallow-submodules https://github.com/taliaga/cicd && cd cicd
          ./build.sh
          ./test.sh
          ./package.sh
      - name: prepare release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./cicd/CHANGELOG.md
          draft: true
          prerelease: false
      - name: upload release artifact
        id: upload-release-artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cicd/release_artifact # generated by package.sh
          asset_name: release_artifact
          asset_content_type: text/plain
      - name: upload release readme
        id: upload-release-readme
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cicd/README.md # available in src
          asset_name: README.md
          asset_content_type: text/plain
      - name: publish release
        id: publish-release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}